config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save

    redirect_to restaurant_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end
  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    @review.save

    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rate, :restaurant_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/edit.html.erb
<div class="container d-flex flex-column align-items-center">
  <h1>Edit a Restaurant</h1>
  <%= link_to 'Back to List', restaurants_path, class: 'btn btn-secondary text-white mb-3' %>

  <div class="col-12 col-sm-6 col-md-3 mb-3 d-flex flex-column gap-4 w-100 p-3">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title"><%= @restaurant.name %></h5>
        <p class="card-text"><%= @restaurant.address %></p>
        <p class="card-text"><%= @restaurant.phone_number %></p>
        <p class="card-text"><%= @restaurant.category %></p>
      </div>
    </div>
    <div class="mt-4 w-20">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: "Choisir une catégorie" %>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row g-3">
    <h1 class="text-center">Restaurant List</h1>

    <%= link_to 'Add New Restaurant', new_restaurant_path, class: 'btn btn-success text-white mb-3 w-100'%>

    <% @restaurants.each do |restaurant| %>
      <div class="col-12 col-sm-6 col-md-3">
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= restaurant.name %></h5>
            <p class="card-text"><%= restaurant.address %></p>
            <p class="card-text"><%= restaurant.phone_number %></p>
            <p class="card-text"><%= restaurant.category %></p>
          </div>
          <div class="card-footer bg-transparent border-0 d-flex flex-wrap gap-2">
            <%= link_to 'View', restaurant_path(restaurant), class: 'btn btn-primary text-white mb-2' %>
            <%= link_to 'Edit', edit_restaurant_path(restaurant), class: 'btn btn-secondary text-white mb-2' %>
            <%= link_to 'Delete', restaurant_path(restaurant), class: 'btn btn-danger text-white mb-2', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="container d-flex flex-column align-items-center">
  <h1>Create a Restaurant</h1>
  <%= link_to 'Back to List', restaurants_path, class: 'btn btn-secondary text-white mb-3' %>

  <div class="col-12 col-sm-6 col-md-3 mb-3 d-flex flex-column gap-4 w-100 p-3">
    <div class="mt-4 w-20">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :phone_number %>
        <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: "Choisir une catégorie" %>
        <%= f.submit class: 'btn btn-primary w-100' %>
      <% end %>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container d-flex flex-column align-items-center">
<h1>Restaurant details</h1>

  <div class="col-12 col-sm-6 col-md-3 mb-3 d-flex flex-column gap-4 w-100 p-3">
    <div class="card h-100">
      <div class="card-body">
        <h5 class="card-title"><%= @restaurant.name %></h5>
        <p class="card-text"><%= @restaurant.address %></p>
        <p class="card-text"><%= @restaurant.phone_number %></p>
        <p class="card-text"><%= @restaurant.category %></p>
      </div>
      <div class="reviews-section p-3">
        <h3>Reviews</h3>
        <div class="d-flex flex-column gap-3">
          <% @restaurant.reviews.each do |review| %>
            <div class="card">
              <div class="card-body">
                <p class="card-text"><strong>Rating:</strong> <%= review.rate %>/5</p>
                <p class="card-text"><strong>Comment:</strong> <%= review.content %></p>
              </div>
            </div>
          <% end %>
      </div>
    </div>
  </div>
  <div class="card-footer bg-transparent border-0 d-flex flex-wrap gap-2">
    <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'btn btn-primary text-white mb-2' %>
    <%= link_to 'Delete', restaurant_path(@restaurant), class: 'btn btn-danger text-white mb-2', data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <%= link_to 'Back to List', restaurants_path, class: 'btn btn-secondary text-white mb-2' %>
    <%= link_to 'Add Review', new_restaurant_review_path(@restaurant), class: 'btn btn-success text-white mb-2' %>
  </div>
</div>

app/views/reviews/new.html.erb
<h1>Ajouter un avis</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rate, collection: [1, 2, 3, 4, 5], prompt: "Choisir une note" %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>